# imports of external packages to use in our code
import sys
import numpy as np
from Random_Class import Random


def generator_Of_Random(seed, number):
    seed = int(seed)
    number= int(number)
   
    # class instance of our Random class using seed
    random = Random(seed)

    # An array of random numbers using our Random class

    f = open("Random.txt","w+")               #Opens the files/creates file
    for i in range(0,number):                 #For a set of data of size N, we loop through and generate N random number
        f.write(np.str(random.rand())+"\n")   #Write to our txt file, Random numbers generated by our random class's function
    f.close()                                 #Close file when the loop is finished.
    return("Random.txt")                      #Returns text file

        
if __name__ == "__main__":
   
    # if the user includes the flag -h or --help print the options
    if '-h' in sys.argv or '--help' in sys.argv:
        print ("Usage: %s [-seed number]" % sys.argv[0])
        print ("Usage: %s [-trial number]" % sys.argv[0])
        sys.exit(1)
        
     # read the user-provided seed from the command line (if there)
    s, n = sys.argv[1:3]
    generator_Of_Random(s, n)
                              


    
     

    